apiVersion: v1
kind: Service
metadata:
    name: "newbot-6d79"
    labels:
        app: "newbot-6d79"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "newbot-6d79"