on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: newbot.azurecr.io
        username: ${{ secrets.acr_newbot_username }}
        password: ${{ secrets.acr_newbot_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t newbot.azurecr.io/newbot:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push newbot.azurecr.io/newbot:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_newbot_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep newbotb7d8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace newbotb7d8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: newbotb7d8
        container-registry-url: newbot.azurecr.io
        container-registry-username: ${{ secrets.acr_newbot_username }}
        container-registry-password: ${{ secrets.acr_newbot_password }}
        secret-name: newbotdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: newbotb7d8
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          newbot.azurecr.io/newbot:${{ github.sha }}
        imagepullsecrets: |
          newbotdockerauth
